import { useState } from "react";
import { Link2, Plus, Undo2 } from "lucide-react";
import type { DataTableColumn } from "../../components/data-table/data-table";
import { Button } from "../../components/ui";
import { useMpgAction } from "./api";
import { MpgDataTable } from "./data-table";
import { MpgFormDialog } from "./form-dialog";
import { dateField, MpgStatus, textField } from "./shared";
import { displayDate, options, statusLabel, type Cylinder, type Device, type Named } from "./types";

export function Cylinders({ cylinders, locations, devices }: { cylinders: Cylinder[]; locations: Named[]; devices: Device[] }) {
  const action = useMpgAction(); const reducers = devices.filter(d => /druckminderer/i.test(`${d.mpgModel?.productType ?? ""} ${d.mpgModel?.name ?? ""}`) && !d.retiredAt); const [createOpen, setCreateOpen] = useState(false); const [assigning, setAssigning] = useState<Cylinder | null>(null); const [returning, setReturning] = useState<Cylinder | null>(null);
  const columns: DataTableColumn<Cylinder>[] = [{ id: "number", label: "Flaschennummer", render: cylinder => <strong>{cylinder.cylinderNumber}</strong>, sortValue: cylinder => cylinder.cylinderNumber }, { id: "supplier", label: "Lieferant", render: cylinder => cylinder.supplier, sortValue: cylinder => cylinder.supplier }, { id: "size", label: "Größe", render: cylinder => `${cylinder.sizeLiters} l`, sortValue: cylinder => cylinder.sizeLiters, width: "90px" }, { id: "location", label: "Standort", render: cylinder => locations.find(location => location.id === cylinder.locationId)?.name ?? cylinder.locationId, sortValue: cylinder => locations.find(location => location.id === cylinder.locationId)?.name ?? "", width: "160px" }, { id: "status", label: "Status", render: cylinder => <MpgStatus value={cylinder.status} />, sortValue: cylinder => statusLabel(cylinder.status), width: "140px" }, { id: "deadlines", label: "Fristen", render: cylinder => <><span>Prüfung {displayDate(cylinder.inspectionDueAt)}</span><small>Verfall {displayDate(cylinder.expiresAt)}</small></>, sortValue: cylinder => cylinder.inspectionDueAt ?? cylinder.expiresAt ?? "", width: "180px" }, { id: "actions", label: "Aktionen", render: cylinder => cylinder.status === "RETURNED" ? "—" : <div className="mpg-row-actions"><Button onClick={() => setAssigning(cylinder)} type="button" variant="secondary"><Link2 data-icon="inline-start" />Zuordnen</Button><Button onClick={() => setReturning(cylinder)} type="button" variant="ghost"><Undo2 data-icon="inline-start" />Rückgabe</Button></div>, width: "230px" }];
  return <section className="mpg-section"><header className="mpg-section-header"><div><h2>Sauerstoffflaschen</h2><p>{cylinders.length} dokumentierte Tauschflaschen</p></div><Button onClick={() => setCreateOpen(true)} type="button"><Plus data-icon="inline-start" />Tauschflasche erfassen</Button></header><p>Tauschflaschen werden getrennt von medizinischem Sauerstoff und eigenen Druckminderern dokumentiert.</p>
    <MpgDataTable columns={columns} emptyMessage="Noch keine Sauerstoffflaschen erfasst." getRowId={cylinder => cylinder.id} rows={cylinders} />
    <MpgFormDialog fields={[textField("supplier", "Lieferant"), textField("cylinderNumber", "Flaschennummer"), { name: "sizeLiters", label: "Größe in Litern", type: "number", required: true, min: 0 }, { name: "locationId", label: "Standort", required: true, options: options(locations) }, { name: "status", label: "Status", required: true, options: ["FULL", "IN_USE", "EMPTY", "RETURNED"].map(value => ({ value, label: statusLabel(value) })) }, dateField("inspectedAt", "Geprüft am"), dateField("inspectionDueAt", "Prüfung fällig"), dateField("expiresAt", "Verfall")]} initial={{ status: "FULL" }} intent="create" onClose={() => setCreateOpen(false)} onSubmit={body => action.mutateAsync({ path: "/cylinders", body })} open={createOpen} size="wide" submitLabel="Tauschflasche erfassen" title="Tauschflasche erfassen" />
    {assigning ? <MpgFormDialog fields={[{ name: "deviceId", label: "Druckminderer", required: true, options: options(reducers) }]} onClose={() => setAssigning(null)} onSubmit={body => action.mutateAsync({ path: `/cylinders/${assigning.id}/assign`, body: { ...body, version: assigning.version } })} open submitLabel="Zuordnung speichern" title={`Druckminderer zu ${assigning.cylinderNumber} zuordnen`} /> : null}
    {returning ? <MpgFormDialog description="Die Flasche wird als zurückgegeben dokumentiert. Ihre Historie bleibt erhalten." fields={[]} onClose={() => setReturning(null)} onSubmit={() => action.mutateAsync({ path: `/cylinders/${returning.id}/return`, body: { version: returning.version } })} open submitLabel="Rückgabe dokumentieren" title={`${returning.cylinderNumber} zurückgeben`} /> : null}
  </section>;
}
