import { useState } from "react";
import { Pencil, Plus, Wrench } from "lucide-react";
import type { DataTableColumn } from "../../components/data-table/data-table";
import { Button } from "../../components/ui";
import { useMpgAction } from "./api";
import { MpgDataTable } from "./data-table";
import { MpgFormDialog } from "./form-dialog";
import { dateField, MpgStatus, textField } from "./shared";
import { displayDate, options, statusLabel, type Device, type Glucose, type Incident, type Person } from "./types";

const incidentFields = [{ ...textField("measures", "Maßnahmen und Behebung"), type: "textarea" as const }, { name: "status", label: "Bearbeitungsstatus", required: true, options: ["OPEN", "RESOLVED"].map(value => ({ value, label: statusLabel(value) })) }, dateField("reportedAt", "Gemeldet am"), textField("reportReference", "Meldereferenz", false)];
const newIncidentFields = [dateField("occurredAt", "Datum", true), { ...textField("description", "Beschreibung"), type: "textarea" as const }, { ...textField("measures", "Getroffene Maßnahmen"), type: "textarea" as const }, { name: "safetyRelevant", label: "Sicherheitsrelevant (sperrt das Gerät)", type: "checkbox" as const }];

export function DeviceControls({ device, people }: { device: Device; people: Person[] }) {
  const action = useMpgAction(); const [createIncident, setCreateIncident] = useState(false); const [editingIncident, setEditingIncident] = useState<Incident | null>(null); const [createControl, setCreateControl] = useState(false); const [resolvingControl, setResolvingControl] = useState<Glucose | null>(null);
  const incidentColumns: DataTableColumn<Incident>[] = [{ id: "date", label: "Datum", render: incident => displayDate(incident.occurredAt), sortValue: incident => incident.occurredAt, width: "130px" }, { id: "description", label: "Vorkommnis", render: incident => <strong>{incident.description}</strong>, sortValue: incident => incident.description }, { id: "status", label: "Status", render: incident => <MpgStatus value={incident.status} />, sortValue: incident => statusLabel(incident.status), width: "120px" }, { id: "action", label: "Aktion", render: incident => <Button onClick={() => setEditingIncident(incident)} type="button" variant="secondary"><Pencil data-icon="inline-start" />Bearbeiten</Button>, width: "150px" }];
  const controlColumns: DataTableColumn<Glucose>[] = [{ id: "date", label: "Durchgeführt", render: control => displayDate(control.performedAt), sortValue: control => control.performedAt, width: "140px" }, { id: "value", label: "Messwert", render: control => <><strong>{control.value} {control.unit}</strong><small>Soll {control.targetMin}–{control.targetMax} {control.unit}</small></>, sortValue: control => control.value }, { id: "result", label: "Ergebnis", render: control => <MpgStatus value={control.passed ? "PASSED" : "FAILED"} />, sortValue: control => control.passed ? 1 : 0, width: "140px" }, { id: "action", label: "Aktion", render: control => !control.passed && !control.resolvedAt ? <Button onClick={() => setResolvingControl(control)} type="button" variant="secondary"><Wrench data-icon="inline-start" />Klären</Button> : "—", width: "130px" }];
  const controlFields = [dateField("performedAt", "Durchgeführt am", true), { name: "personId", label: "Ausführende Person", required: true, options: options(people.filter(person => person.active)) }, textField("stripLot", "Teststreifencharge"), textField("solutionName", "Kontrolllösung"), textField("solutionLot", "Charge der Kontrolllösung"), dateField("solutionExpiresAt", "Verfall der Kontrolllösung", true), textField("controlLevel", "Kontrollniveau"), { name: "unit", label: "Einheit", required: true, options: ["mg/dL", "mmol/L"].map(value => ({ value, label: value })) }, ...[{ name: "targetMin", label: "Sollbereich von" }, { name: "targetMax", label: "Sollbereich bis" }, { name: "value", label: "Messwert" }].map(field => ({ ...field, type: "number" as const, required: true, min: 0 }))];
  return <><section className="mpg-detail-section"><header><div><h3>Defekte und Vorkommnisse</h3><p>Sicherheitsrelevante Einträge sperren das Gerät.</p></div><Button onClick={() => setCreateIncident(true)} type="button"><Plus data-icon="inline-start" />Vorkommnis erfassen</Button></header><MpgDataTable columns={incidentColumns} emptyMessage="Keine Defekte oder Vorkommnisse dokumentiert." getRowId={incident => incident.id} rows={device.incidents} /></section>
    <section className="mpg-detail-section"><header><div><h3>BZ-Qualitätskontrollen</h3><p>Kontrollmessungen ohne Patientenwerte.</p></div><Button onClick={() => setCreateControl(true)} type="button"><Plus data-icon="inline-start" />Kontrollmessung</Button></header><MpgDataTable columns={controlColumns} emptyMessage="Noch keine BZ-Kontrollmessungen dokumentiert." getRowId={control => control.id} rows={device.glucoseControls} /></section>
    <MpgFormDialog fields={newIncidentFields} initial={{ safetyRelevant: true }} intent="create" onClose={() => setCreateIncident(false)} onSubmit={body => action.mutateAsync({ path: `/devices/${device.id}/incidents`, body })} open={createIncident} size="wide" submitLabel="Vorkommnis dokumentieren" title="Defekt oder Vorkommnis erfassen" />
    {editingIncident ? <MpgFormDialog fields={incidentFields} initial={{ measures: editingIncident.measures, status: editingIncident.status, reportReference: editingIncident.reportReference ?? "", reportedAt: editingIncident.reportedAt?.slice(0, 10) ?? "" }} onClose={() => setEditingIncident(null)} onSubmit={body => action.mutateAsync({ path: `/incidents/${editingIncident.id}`, method: "PATCH", body: { ...body, version: editingIncident.version } })} open size="wide" submitLabel="Maßnahmen speichern" title="Vorkommnis bearbeiten" /> : null}
    <MpgFormDialog fields={controlFields} intent="create" onClose={() => setCreateControl(false)} onSubmit={body => action.mutateAsync({ path: `/devices/${device.id}/glucose-controls`, body: { ...body, targetUnit: body.unit } })} open={createControl} size="wide" submitLabel="Messung dokumentieren" title="BZ-Kontrollmessung erfassen" />
    {resolvingControl ? <MpgFormDialog fields={[textField("clarification", "Ursache und Korrekturmaßnahmen")]} onClose={() => setResolvingControl(null)} onSubmit={body => action.mutateAsync({ path: `/glucose-controls/${resolvingControl.id}/resolve`, body })} open submitLabel="Klärung dokumentieren" title="Fehlerklärung nach erfolgreicher Wiederholung" /> : null}
  </>;
}
