import { useMpgAction } from "./api";
import { MpgForm } from "./form";
import { dateField, textField } from "./shared";
import { displayDate, options, statusLabel, type Device, type Person } from "./types";
export function DeviceControls({ device, people }: { device: Device; people: Person[] }) {
  const action = useMpgAction();
  return <><section><h3>Defekte und Vorkommnisse</h3>{device.incidents.map((incident) => <details key={incident.id} className="mpg-detail"><summary>{displayDate(incident.occurredAt)} · {incident.description} · {statusLabel(incident.status)}</summary><MpgForm key={`${incident.id}-${incident.version}`} title="Maßnahmen dokumentieren" initial={{ measures: incident.measures, status: incident.status, reportReference: incident.reportReference ?? "", reportedAt: incident.reportedAt?.slice(0, 10) ?? "" }} fields={[{ ...textField("measures", "Maßnahmen und Behebung"), type: "textarea" }, { name: "status", label: "Bearbeitungsstatus", required: true, options: ["OPEN", "RESOLVED"].map((value) => ({ value, label: statusLabel(value) })) }, dateField("reportedAt", "Gemeldet am"), textField("reportReference", "Meldereferenz", false)]} onSubmit={(body) => action.mutateAsync({ path: `/incidents/${incident.id}`, method: "PATCH", body: { ...body, version: incident.version } })} /></details>)}
    <details className="mpg-detail"><summary>Defekt oder Vorkommnis erfassen</summary><MpgForm title="Vorkommnis dokumentieren" initial={{ safetyRelevant: true }} fields={[dateField("occurredAt", "Datum", true), { ...textField("description", "Beschreibung"), type: "textarea" }, { ...textField("measures", "Getroffene Maßnahmen"), type: "textarea" }, { name: "safetyRelevant", label: "Sicherheitsrelevant (sperrt das Gerät)", type: "checkbox" }]} onSubmit={(body) => action.mutateAsync({ path: `/devices/${device.id}/incidents`, body })} /></details></section>
    <section><h3>BZ-Qualitätskontrollen</h3><p>Nur Kontrollmessungen dokumentieren, keine Patientenwerte.</p>{device.glucoseControls.map((control) => <details className="mpg-detail" key={control.id}><summary>{displayDate(control.performedAt)} · {control.value} {control.unit} · {control.passed ? "Bestanden" : "Nicht bestanden"}</summary><p>Sollbereich: {control.targetMin}–{control.targetMax} {control.unit}</p>{!control.passed && !control.resolvedAt ? <MpgForm title="Fehlerklärung nach erfolgreicher Wiederholung" fields={[textField("clarification", "Ursache und Korrekturmaßnahmen")]} onSubmit={(body) => action.mutateAsync({ path: `/glucose-controls/${control.id}/resolve`, body })} /> : <p>{control.clarification}</p>}</details>)}
      <details className="mpg-detail"><summary>Kontrollmessung erfassen</summary><MpgForm title="BZ-Kontrollmessung" fields={[dateField("performedAt", "Durchgeführt am", true), { name: "personId", label: "Ausführende Person", required: true, options: options(people.filter((person) => person.active)) }, textField("stripLot", "Teststreifencharge"), textField("solutionName", "Kontrolllösung"), textField("solutionLot", "Charge der Kontrolllösung"), dateField("solutionExpiresAt", "Verfall der Kontrolllösung", true), textField("controlLevel", "Kontrollniveau"), { name: "unit", label: "Einheit", required: true, options: ["mg/dL", "mmol/L"].map((value) => ({ value, label: value })) }, ...[{ name: "targetMin", label: "Sollbereich von" }, { name: "targetMax", label: "Sollbereich bis" }, { name: "value", label: "Messwert" }].map((field) => ({ ...field, type: "number" as const, required: true, min: 0 }))]} submitLabel="Messung verbindlich dokumentieren" onSubmit={(body) => action.mutateAsync({ path: `/devices/${device.id}/glucose-controls`, body: { ...body, targetUnit: body.unit } })} /></details>
    </section></>;
}
