import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { AnchorButton, Field } from "../../components/ui";
import { useMpgAction } from "./api";
import { MpgForm, type FormField } from "./form";
import { dateField, MpgTable, textField } from "./shared";
import { Models } from "./models";
import { options, statusLabel, type Device, type Model, type Named, type Person } from "./types";
export type Catalog = { locations: Named[]; kits: Named[]; articles: Named[]; people: Person[]; models: Model[] };
export function deviceFields(catalog: Catalog): FormField[] { return [textField("name", "Gerätename"), { name: "articleId", label: "Artikel", required: true, options: options(catalog.articles) }, { name: "mpgModelId", label: "Modell", options: options(catalog.models) }, textField("inventoryNumber", "Inventarnummer"), textField("serialNumber", "Seriennummer / Loscode"), { name: "acquisitionYear", label: "Anschaffungsjahr", type: "number", min: 1900, max: new Date().getFullYear() }, dateField("commissionedAt", "Inbetriebnahme"), { name: "locationId", label: "Standort", required: true, options: options(catalog.locations) }, { name: "kitId", label: "Rucksack", options: options(catalog.kits) }, { name: "responsiblePersonId", label: "Zuständige Person", options: options(catalog.people) }, { name: "notes", label: "Notizen", type: "textarea" }]; }
export function Devices({ devices, catalog }: { devices: Device[]; catalog: Catalog }) {
  const [search, setSearch] = useState(""); const [location, setLocation] = useState(""); const [kit, setKit] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [due, setDue] = useState(""); const action = useMpgAction();
  const today = new Date().toISOString().slice(0, 10), inThirtyDays = new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10);
  const filtered = devices.filter((device) => `${device.name} ${device.inventoryNumber ?? ""} ${device.serialNumber ?? ""}`.toLocaleLowerCase("de").includes(search.toLocaleLowerCase("de")) && (!location || device.locationId === location) && (!kit || device.kitId === kit) && (!type || device.mpgModel?.productType === type) && (!status || device.status === status) && (!due || matchesDue(device, due, today, inThirtyDays)));
  return <><div className="mpg-actions"><AnchorButton variant="secondary" href="/api/mpg/exports/inventory.pdf">Bestandsverzeichnis PDF</AnchorButton><AnchorButton variant="ghost" href="/api/mpg/exports/inventory.csv">CSV</AnchorButton></div>
    <div className="mpg-fields" role="search" aria-label="Geräte filtern"><Field label="Suche"><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} /></Field>{[{ label: "Standort", value: location, set: setLocation, options: options(catalog.locations) }, { label: "Rucksack", value: kit, set: setKit, options: options(catalog.kits) }, { label: "Gerätetyp", value: type, set: setType, options: [...new Set(catalog.models.map((model) => model.productType))].map((value) => ({ value, label: value })) }, { label: "Status", value: status, set: setStatus, options: ["DRAFT", "BLOCKED", "RELEASED", "RETIRED"].map((value) => ({ value, label: statusLabel(value) })) }, { label: "Prüffälligkeit", value: due, set: setDue, options: [{ value: "OVERDUE", label: "Überfällig" }, { value: "SOON", label: "In 30 Tagen" }, { value: "MISSING", label: "Fälligkeit fehlt" }] }].map((filter) => <Field key={filter.label} label={filter.label}><select value={filter.value} onChange={(event) => filter.set(event.target.value)}><option value="">Alle</option>{filter.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>)}</div>
    <MpgTable headings={["Gerät", "Inventarnummer", "Standort", "Status", ""]} empty={filtered.length === 0}>{filtered.map((device) => <tr key={device.id}><td>{device.name}<br /><small>{device.mpgModel?.name}</small></td><td>{device.inventoryNumber}</td><td>{device.location?.name ?? catalog.locations.find((entry) => entry.id === device.locationId)?.name}</td><td>{statusLabel(device.status)}</td><td><Link to="/admin/mpg" search={{ view: "devices", device: device.id }}>Geräteakte öffnen</Link></td></tr>)}</MpgTable>
    <details className="mpg-detail"><summary>Gerät erfassen</summary><MpgForm title="Neues Gerät" fields={deviceFields(catalog)} onSubmit={(body) => action.mutateAsync({ path: "/devices", body })} /></details><Models models={catalog.models} />
  </>;
}
function matchesDue(device: Device, filter: string, today: string, inThirtyDays: string) { const due = (device.requirements ?? []).filter(r => r.mandatory).map(r => r.dueDate); if (filter === "MISSING") return due.some(value => !value); if (filter === "OVERDUE") return due.some(value => value && value < today); return due.some(value => value && value >= today && value <= inThirtyDays); }
