import { useMpg, useMpgAction } from "./api";
import { MpgForm, type FormField } from "./form";
import { dateField, textField } from "./shared";
import { displayDate, options, statusLabel, type Device, type Document, type Person, type Inspection } from "./types";
function inspectionFields(device: Device, people: Person[], documents: Document[]): FormField[] { return [{ name: "requirementId", label: "Prüfanforderung", required: true, options: device.mpgModel?.requirements.map((requirement) => ({ value: requirement.id, label: `${requirement.kind} · ${requirement.title}` })) ?? [] }, dateField("performedAt", "Durchführungstag", true), { name: "result", label: "Ergebnis", required: true, options: ["PASSED", "FAILED"].map((value) => ({ value, label: statusLabel(value) })) }, { name: "personId", label: "Interne prüfende Person", options: options(people) }, textField("externalCompany", "Externe Prüffirma", false), textField("qualification", "Qualifikation / Nachweis", false), { name: "reportDocumentId", label: "Prüfbericht", required: true, options: documents.map((document) => ({ value: document.id, label: `${document.filename} · v${document.version}` })) }, dateField("nextDueAt", "Nächste Fälligkeit"), { name: "notes", label: "Bemerkungen", type: "textarea" }]; }
export function Inspections({ device, people }: { device: Device; people: Person[] }) {
  const documents = useMpg<Document[]>(`/documents?deviceId=${device.id}`); const action = useMpgAction(); const fields = inspectionFields(device, people, documents.data ?? []);
  const values = (inspection: Inspection) => Object.fromEntries(Object.entries(inspection).filter(([key, value]) => fields.some((field) => field.name === key) && (typeof value === "string" || typeof value === "number")).map(([key, value]) => [key, key.endsWith("At") ? String(value).slice(0, 10) : value])) as Record<string, string | number>;
  return <section><h3>Prüfungen und Wartung</h3><p>Berichte zuerst unter Dokumente hochladen. Entwürfe beeinflussen die Freigabe noch nicht.</p>
    {device.inspections.map((inspection) => <details className="mpg-detail" key={inspection.id}><summary>{inspection.requirement?.title ?? "Prüfung"} · {displayDate(inspection.performedAt)} · {statusLabel(inspection.result)} · {inspection.finalizedAt ? "Abgeschlossen" : "Entwurf"}</summary>
      {inspection.finalizedAt ? <><p>{inspection.notes}</p><MpgForm title="Berichtigung als Nachtrag" initial={values(inspection)} fields={[...fields, textField("reason", "Berichtigungsgrund")]} onSubmit={(body) => action.mutateAsync({ path: `/inspections/${inspection.id}/correct`, body })} /></> : <><MpgForm title="Prüfentwurf bearbeiten" initial={values(inspection)} fields={fields} onSubmit={(body) => action.mutateAsync({ path: `/inspections/${inspection.id}`, method: "PATCH", body: { ...body, version: inspection.version } })} /><MpgForm title="Nachweis abschließen" fields={[]} submitLabel="Verbindlich abschließen" onSubmit={() => action.mutateAsync({ path: `/inspections/${inspection.id}/finalize`, body: { version: inspection.version } })} /></>}
    </details>)}
    <details className="mpg-detail"><summary>Prüfung erfassen</summary><MpgForm title="Neuer Prüfentwurf" fields={fields} onSubmit={(body) => action.mutateAsync({ path: `/devices/${device.id}/inspections`, body })} /></details>
  </section>;
}
