import { useState } from "react";
import { CheckCircle2, Pencil, Plus, RotateCcw } from "lucide-react";
import type { DataTableColumn } from "../../components/data-table/data-table";
import { Button } from "../../components/ui";
import { useMpg, useMpgAction } from "./api";
import { MpgDataTable } from "./data-table";
import { MpgFormDialog } from "./form-dialog";
import { dateField, MpgStatus, textField } from "./shared";
import { displayDate, options, statusLabel, type Device, type Document, type Person, type Inspection } from "./types";

function inspectionFields(device: Device, people: Person[], documents: Document[]) { return [{ name: "requirementId", label: "Prüfanforderung", required: true, options: (device.requirements ?? []).map(requirement => ({ value: requirement.id, label: `${requirement.kind} · ${requirement.title}` })) }, dateField("performedAt", "Durchführungstag", true), { name: "result", label: "Ergebnis", required: true, options: ["PASSED", "FAILED"].map(value => ({ value, label: statusLabel(value) })) }, { name: "personId", label: "Interne prüfende Person", options: options(people.filter(person => person.active)) }, textField("externalName", "Name der externen prüfenden Person", false), textField("externalCompany", "Externe Prüffirma", false), textField("qualification", "Qualifikation / Nachweis", false), { name: "reportDocumentId", label: "Prüfbericht (optional)", options: documents.map(document => ({ value: document.id, label: `${document.filename} · v${document.version}` })) }, dateField("nextDueAt", "Nächste Fälligkeit", true), { name: "notes", label: "Bemerkungen", type: "textarea" as const }]; }

export function Inspections({ device, people }: { device: Device; people: Person[] }) {
  const documents = useMpg<Document[]>(`/documents?deviceId=${device.id}`); const action = useMpgAction(); const fields = inspectionFields(device, people, documents.data ?? []); const [selectedId, setSelectedId] = useState(""); const [dialog, setDialog] = useState<"create" | "edit" | "correct" | "finalize" | null>(null);
  const selected = device.inspections.find(inspection => inspection.id === selectedId) ?? device.inspections[0] ?? null;
  const values = (inspection: Inspection) => Object.fromEntries(Object.entries(inspection).filter(([key, value]) => fields.some(field => field.name === key) && (typeof value === "string" || typeof value === "number")).map(([key, value]) => [key, key.endsWith("At") ? String(value).slice(0, 10) : value])) as Record<string, string | number>;
  const columns: DataTableColumn<Inspection>[] = [{ id: "inspection", label: "Prüfung", render: inspection => <strong>{inspection.requirement?.title ?? "Prüfung"}</strong>, sortValue: inspection => inspection.requirement?.title ?? "" }, { id: "date", label: "Durchgeführt", render: inspection => displayDate(inspection.performedAt), sortValue: inspection => inspection.performedAt, width: "140px" }, { id: "result", label: "Ergebnis", render: inspection => <MpgStatus value={inspection.result} />, sortValue: inspection => statusLabel(inspection.result), width: "140px" }, { id: "record", label: "Nachweis", render: inspection => inspection.finalizedAt ? "Abgeschlossen" : "Entwurf", sortValue: inspection => inspection.finalizedAt ? 1 : 0, width: "140px" }];
  return <section className="mpg-detail-section"><header><div><h3>Prüfungen und Wartung</h3><p>Entwürfe beeinflussen die Freigabe noch nicht.</p></div><Button onClick={() => setDialog("create")} type="button"><Plus data-icon="inline-start" />Prüfung erfassen</Button></header><MpgDataTable columns={columns} emptyMessage="Noch keine Prüfungen dokumentiert." getRowId={inspection => inspection.id} onRowClick={inspection => setSelectedId(inspection.id)} rows={device.inspections} selectedRowId={selected?.id} />
    {selected ? <div className="mpg-selected-detail"><div><strong>{selected.requirement?.title ?? "Prüfung"}</strong><p>{selected.notes || "Keine Bemerkungen"}</p></div><div className="mpg-row-actions">{selected.finalizedAt ? <Button onClick={() => setDialog("correct")} type="button" variant="secondary"><RotateCcw data-icon="inline-start" />Nachtrag</Button> : <><Button onClick={() => setDialog("edit")} type="button" variant="secondary"><Pencil data-icon="inline-start" />Entwurf bearbeiten</Button><Button onClick={() => setDialog("finalize")} type="button"><CheckCircle2 data-icon="inline-start" />Abschließen</Button></>}</div></div> : null}
    <MpgFormDialog fields={fields} intent="create" onClose={() => setDialog(null)} onSubmit={body => action.mutateAsync({ path: `/devices/${device.id}/inspections`, body })} open={dialog === "create"} size="wide" submitLabel="Prüfentwurf anlegen" title="Prüfung erfassen" />
    {selected ? <><MpgFormDialog fields={fields} initial={values(selected)} onClose={() => setDialog(null)} onSubmit={body => action.mutateAsync({ path: `/inspections/${selected.id}`, method: "PATCH", body: { ...body, version: selected.version } })} open={dialog === "edit"} size="wide" submitLabel="Entwurf speichern" title="Prüfentwurf bearbeiten" /><MpgFormDialog fields={[...fields, textField("reason", "Berichtigungsgrund")]} initial={values(selected)} onClose={() => setDialog(null)} onSubmit={body => action.mutateAsync({ path: `/inspections/${selected.id}/correct`, body })} open={dialog === "correct"} size="wide" submitLabel="Nachtrag speichern" title="Berichtigung als Nachtrag" /><MpgFormDialog description="Der Nachweis wird unveränderlich abgeschlossen und beeinflusst anschließend Fälligkeit und Gerätestatus." fields={[]} onClose={() => setDialog(null)} onSubmit={() => action.mutateAsync({ path: `/inspections/${selected.id}/finalize`, body: { version: selected.version } })} open={dialog === "finalize"} submitLabel="Verbindlich abschließen" title="Prüfnachweis abschließen" /></> : null}
  </section>;
}
