import { useState } from "react";
import { CheckCircle2, FileSignature, Plus } from "lucide-react";
import type { DataTableColumn } from "../../components/data-table/data-table";
import { AnchorButton, Button } from "../../components/ui";
import { useMpgAction } from "./api";
import type { Catalog } from "./devices";
import { MpgDataTable } from "./data-table";
import { MpgFormDialog } from "./form-dialog";
import { Signature } from "./signature";
import { dateField, textField } from "./shared";
import { displayDate, options, type Device, type Training } from "./types";

export function Trainings({ catalog, devices, trainings = [], deviceId }: { catalog: Catalog; devices: Device[]; trainings?: Training[]; deviceId?: string }) {
  const action = useMpgAction(); const [createOpen, setCreateOpen] = useState(false); const [selectedId, setSelectedId] = useState(""); const [confirmOpen, setConfirmOpen] = useState(false); const [finalizeOpen, setFinalizeOpen] = useState(false); const [signature, setSignature] = useState("");
  const visible = deviceId ? trainings.filter(training => training.deviceId === deviceId || training.modelId === devices[0]?.mpgModelId) : trainings; const selected = visible.find(training => training.id === selectedId) ?? visible[0] ?? null;
  const columns: DataTableColumn<Training>[] = [{ id: "date", label: "Datum", render: training => displayDate(training.performedAt), sortValue: training => training.performedAt, width: "140px" }, { id: "scope", label: "Geltungsbereich", render: training => <strong>{training.scope}</strong>, sortValue: training => training.scope }, { id: "confirmations", label: "Bestätigungen", render: training => `${training.confirmations.filter(confirmation => confirmation.confirmedAt).length}/${training.confirmations.length}`, sortValue: training => training.confirmations.filter(confirmation => confirmation.confirmedAt).length, width: "150px" }, { id: "status", label: "Status", render: training => <span className={`mpg-status mpg-status-${training.finalizedAt ? "ready" : "warning"}`}>{training.finalizedAt ? "Abgeschlossen" : "Offen"}</span>, sortValue: training => training.finalizedAt ? 1 : 0, width: "140px" }];
  return <section className="mpg-section"><header className="mpg-section-header"><div><h2>Einweisungen</h2><p>{visible.length} Einweisungsnachweise</p></div><Button onClick={() => setCreateOpen(true)} type="button"><Plus data-icon="inline-start" />Einweisung anlegen</Button></header><MpgDataTable columns={columns} emptyMessage="Noch keine Einweisungen dokumentiert." getRowId={training => training.id} onRowClick={training => setSelectedId(training.id)} rows={visible} selectedRowId={selected?.id} />
    {selected ? <section className="mpg-detail-section"><header><div><h3>{selected.scope}</h3><p>{displayDate(selected.performedAt)} · {selected.confirmations.filter(confirmation => confirmation.confirmedAt).length}/{selected.confirmations.length} bestätigt</p></div><div className="mpg-row-actions">{selected.finalizedAt ? <AnchorButton variant="secondary" href={`/api/mpg/exports/trainings/${selected.id}.pdf`}>PDF herunterladen</AnchorButton> : <><Button onClick={() => { setSignature(""); setConfirmOpen(true); }} type="button" variant="secondary"><FileSignature data-icon="inline-start" />Bestätigung erfassen</Button>{selected.confirmations.every(confirmation => confirmation.confirmedAt) ? <Button onClick={() => setFinalizeOpen(true)} type="button"><CheckCircle2 data-icon="inline-start" />Abschließen</Button> : null}</>}</div></header><div className="mpg-confirmation-list">{selected.confirmations.map(confirmation => <div key={confirmation.id}><strong>{confirmation.nameSnapshot}</strong><span>{confirmation.confirmedAt ? `Bestätigt am ${displayDate(confirmation.confirmedAt)}` : "Bestätigung offen"}</span></div>)}</div></section> : null}
    <MpgFormDialog intent="create" onClose={() => setCreateOpen(false)} open={createOpen} size="wide" submitLabel="Einweisung anlegen" title="Einweisung anlegen" initial={deviceId ? { deviceId } : {}} fields={[{ name: "modelId", label: "Modell", required: true, options: options(catalog.models) }, { name: "deviceId", label: "Optionales Einzelgerät", options: options(devices) }, dateField("performedAt", "Datum", true), { name: "instructorId", label: "Einweisende Person", required: true, options: options(catalog.people.filter(person => person.active && person.instructorAuthorization)) }, { name: "documentId", label: "Verwendete Gebrauchsanweisung", required: true, options: catalog.models.filter(model => model.instructionsDocumentId).map(model => ({ value: model.instructionsDocumentId!, label: `${model.manufacturer} · ${model.name}` })) }, textField("scope", "Geltungsbereich"), { ...textField("contents", "Inhalte"), type: "textarea" }, { name: "participantIds", label: "Teilnehmer", required: true, options: options(catalog.people.filter(person => person.active)), multiple: true }]} onSubmit={body => action.mutateAsync({ path: "/trainings", body })} />
    {selected ? <><MpgFormDialog fields={[{ name: "confirmationId", label: "Beteiligte Person", required: true, options: selected.confirmations.filter(confirmation => !confirmation.confirmedAt).map(confirmation => ({ value: confirmation.id, label: confirmation.nameSnapshot })) }, { name: "confirmationText", label: "Bestätigungstext", required: true, type: "textarea" }]} initial={{ confirmationText: "Ich bestätige die persönliche Teilnahme und Einweisung in den angegebenen Geltungsbereich." }} onClose={() => setConfirmOpen(false)} onSubmit={body => { const confirmation = selected.confirmations.find(entry => entry.id === body.confirmationId); if (!confirmation) throw new Error("Bitte eine Person auswählen."); if (!signature) throw new Error("Bitte persönlich unterschreiben."); return action.mutateAsync({ path: `/trainings/${selected.id}/confirm`, body: { version: selected.version, personId: confirmation.personId, role: confirmation.role, confirmationText: body.confirmationText, signaturePngDataUrl: signature } }); }} open={confirmOpen} size="wide" submitLabel="Bestätigung speichern" title="Teilnahme bestätigen"><Signature onChange={setSignature} /></MpgFormDialog><MpgFormDialog description="Nach dem Abschluss bleibt der Einweisungsnachweis unverändert." fields={[]} onClose={() => setFinalizeOpen(false)} onSubmit={() => action.mutateAsync({ path: `/trainings/${selected.id}/finalize`, body: { version: selected.version } })} open={finalizeOpen} submitLabel="Einweisung abschließen" title="Einweisung verbindlich abschließen" /></> : null}
  </section>;
}
