import { useState } from "react";
import { CheckCircle2, FileSignature, Plus, RotateCcw } from "lucide-react";
import type { DataTableColumn } from "../../components/data-table/data-table";
import { AnchorButton, Button } from "../../components/ui";
import { useMpgAction } from "./api";
import type { Catalog } from "./devices";
import { MpgDataTable } from "./data-table";
import { MpgFormDialog } from "./form-dialog";
import { Signature } from "./signature";
import { dateField, textField } from "./shared";
import { displayDate, options, type Training } from "./types";

export function Trainings({ catalog, trainings = [], modelId }: { catalog: Catalog; trainings?: Training[]; modelId?: string }) {
  const action = useMpgAction(); const [createOpen, setCreateOpen] = useState(false); const [correctionOpen, setCorrectionOpen] = useState(false); const [selectedId, setSelectedId] = useState(""); const [confirmOpen, setConfirmOpen] = useState(false); const [finalizeOpen, setFinalizeOpen] = useState(false); const [signature, setSignature] = useState("");
  const visible = modelId ? trainings.filter(training => training.modelId === modelId) : trainings; const selected = visible.find(training => training.id === selectedId) ?? visible[0] ?? null;
  const modelName = (id: string) => { const model = catalog.models.find(entry => entry.id === id); return model ? `${model.manufacturer} · ${model.name}` : "Unbekanntes Modell"; };
  const fields = [{ name: "modelId", label: "Modell", required: true, options: options(catalog.models) }, dateField("performedAt", "Datum", true), { name: "instructorId", label: "Einweisende Person", required: true, options: options(catalog.people.filter(canInstruct)) }, { name: "documentId", label: "Verwendete Dokumentversion (optional)", options: catalog.models.filter(model => model.instructionsDocumentId).map(model => ({ value: model.instructionsDocumentId!, label: `${model.manufacturer} · ${model.name}` })) }, { ...textField("contents", "Inhalte"), type: "textarea" as const }, { name: "participantIds", label: "Teilnehmer", required: true, options: options(catalog.people.filter(person => person.active)), multiple: true }];
  const columns: DataTableColumn<Training>[] = [{ id: "date", label: "Datum", render: training => displayDate(training.performedAt), sortValue: training => training.performedAt, width: "140px" }, { id: "model", label: "Modell", render: training => <strong>{modelName(training.modelId)}</strong>, sortValue: training => modelName(training.modelId) }, { id: "confirmations", label: "Bestätigungen", render: training => `${training.confirmations.filter(confirmation => confirmation.confirmedAt).length}/${training.confirmations.length}`, sortValue: training => training.confirmations.filter(confirmation => confirmation.confirmedAt).length, width: "150px" }, { id: "status", label: "Status", render: training => <span className={`mpg-status mpg-status-${training.finalizedAt ? "ready" : "warning"}`}>{training.finalizedAt ? "Abgeschlossen" : "Offen"}</span>, sortValue: training => training.finalizedAt ? 1 : 0, width: "140px" }];
  return <section className="mpg-section"><header className="mpg-section-header"><div><h2>Einweisungen</h2><p>{visible.length} Einweisungsnachweise</p></div><Button onClick={() => setCreateOpen(true)} type="button"><Plus data-icon="inline-start" />Einweisung anlegen</Button></header><MpgDataTable columns={columns} emptyMessage="Noch keine Einweisungen dokumentiert." getRowId={training => training.id} onRowClick={training => setSelectedId(training.id)} rows={visible} selectedRowId={selected?.id} />
    {selected ? <section className="mpg-detail-section"><header><div><h3>{modelName(selected.modelId)}</h3><p>{displayDate(selected.performedAt)} · {selected.confirmations.filter(confirmation => confirmation.confirmedAt).length}/{selected.confirmations.length} bestätigt</p></div><div className="mpg-row-actions">{selected.finalizedAt ? <><AnchorButton variant="secondary" href={`/api/mpg/exports/trainings/${selected.id}.pdf`}>PDF herunterladen</AnchorButton><Button onClick={() => setCorrectionOpen(true)} type="button" variant="secondary"><RotateCcw data-icon="inline-start" />Nachtrag</Button></> : <><Button onClick={() => { setSignature(""); setConfirmOpen(true); }} type="button" variant="secondary"><FileSignature data-icon="inline-start" />Bestätigung erfassen</Button>{selected.confirmations.every(confirmation => confirmation.confirmedAt) ? <Button onClick={() => setFinalizeOpen(true)} type="button"><CheckCircle2 data-icon="inline-start" />Abschließen</Button> : null}</>}</div></header><p>{selected.contents}</p><div className="mpg-confirmation-list">{selected.confirmations.map(confirmation => <div key={confirmation.id}><strong>{confirmation.nameSnapshot}</strong><span>{confirmation.role === "INSTRUCTOR" ? "Einweisende Person" : "Teilnehmende Person"} · {confirmation.confirmedAt ? `bestätigt am ${displayDate(confirmation.confirmedAt)}` : "Bestätigung offen"}</span></div>)}</div></section> : null}
    <MpgFormDialog intent="create" onClose={() => setCreateOpen(false)} open={createOpen} size="wide" submitLabel="Einweisung anlegen" title="Einweisung anlegen" initial={modelId ? { modelId } : {}} fields={fields} onSubmit={body => action.mutateAsync({ path: "/trainings", body })} />
    {selected?.finalizedAt ? <MpgFormDialog fields={[...fields, textField("reason", "Berichtigungsgrund")]} initial={{ modelId: selected.modelId, performedAt: selected.performedAt.slice(0, 10), instructorId: selected.instructorId, documentId: selected.documentId ?? "", contents: selected.contents, participantIds: selected.confirmations.filter(confirmation => confirmation.role === "PARTICIPANT").map(confirmation => confirmation.personId) }} onClose={() => setCorrectionOpen(false)} onSubmit={body => action.mutateAsync({ path: "/trainings", body: { ...body, correctionOfId: selected.id } })} open={correctionOpen} size="wide" submitLabel="Nachtrag anlegen" title="Einweisung berichtigen" /> : null}
    {selected ? <><MpgFormDialog fields={[{ name: "confirmationId", label: "Beteiligte Person", required: true, options: selected.confirmations.filter(confirmation => !confirmation.confirmedAt).map(confirmation => ({ value: confirmation.id, label: confirmation.nameSnapshot })) }, { name: "confirmationText", label: "Bestätigungstext", required: true, type: "textarea" }]} initial={{ confirmationText: "Ich bestätige die persönliche Teilnahme und Einweisung in das angegebene Modell." }} onClose={() => setConfirmOpen(false)} onSubmit={body => { const confirmation = selected.confirmations.find(entry => entry.id === body.confirmationId); if (!confirmation) throw new Error("Bitte eine Person auswählen."); if (!signature) throw new Error("Bitte persönlich unterschreiben."); return action.mutateAsync({ path: `/trainings/${selected.id}/confirm`, body: { version: selected.version, personId: confirmation.personId, role: confirmation.role, confirmationText: body.confirmationText, signaturePngDataUrl: signature } }); }} open={confirmOpen} size="wide" submitLabel="Bestätigung speichern" title="Teilnahme bestätigen"><Signature onChange={setSignature} /></MpgFormDialog><MpgFormDialog description="Nach dem Abschluss bleibt der Einweisungsnachweis unverändert." fields={[]} onClose={() => setFinalizeOpen(false)} onSubmit={() => action.mutateAsync({ path: `/trainings/${selected.id}/finalize`, body: { version: selected.version } })} open={finalizeOpen} submitLabel="Einweisung abschließen" title="Einweisung verbindlich abschließen" /></> : null}
  </section>;
}

function canInstruct(person: Catalog["people"][number]) {
  return person.active && person.instructorAuthorized && Boolean(person.instructorAuthorization) && Boolean(person.qualificationDocumentId) && (!person.authorizationValidUntil || new Date(person.authorizationValidUntil) >= new Date());
}
