/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset/index'
import { Route as PasswordResetTokenRouteImport } from './routes/password-reset/$token'
import { Route as InvitationTokenRouteImport } from './routes/invitation/$token'
import { Route as CheckTokenRouteImport } from './routes/check/$token'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMasterDataRouteImport } from './routes/admin/master-data'
import { Route as AdminKitsRouteImport } from './routes/admin/kits'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminAccountRouteImport } from './routes/admin/account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetTokenRoute = PasswordResetTokenRouteImport.update({
  id: '/password-reset/$token',
  path: '/password-reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckTokenRoute = CheckTokenRouteImport.update({
  id: '/check/$token',
  path: '/check/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/admin/kits',
  path: '/admin/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset/': typeof PasswordResetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset': typeof PasswordResetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/master-data': typeof AdminMasterDataRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset/': typeof PasswordResetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/account'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/master-data'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/password-reset/$token'
    | '/password-reset/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/account'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/master-data'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/password-reset/$token'
    | '/password-reset'
  id:
    | '__root__'
    | '/'
    | '/admin/account'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/master-data'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/password-reset/$token'
    | '/password-reset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminMasterDataRoute: typeof AdminMasterDataRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CheckTokenRoute: typeof CheckTokenRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  PasswordResetTokenRoute: typeof PasswordResetTokenRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/$token': {
      id: '/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/$token': {
      id: '/check/$token'
      path: '/check/$token'
      fullPath: '/check/$token'
      preLoaderRoute: typeof CheckTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/admin/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminMasterDataRoute: AdminMasterDataRoute,
  AdminUsersRoute: AdminUsersRoute,
  CheckTokenRoute: CheckTokenRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  PasswordResetTokenRoute: PasswordResetTokenRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
