/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasswordResetIndexRouteImport } from './routes/password-reset/index'
import { Route as PasswordResetTokenRouteImport } from './routes/password-reset/$token'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImprintRouteImport } from './routes/legal/imprint'
import { Route as InvitationTokenRouteImport } from './routes/invitation/$token'
import { Route as CheckTokenRouteImport } from './routes/check/$token'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPurchaseOrdersRouteImport } from './routes/admin/purchase-orders'
import { Route as AdminMasterDataRouteImport } from './routes/admin/master-data'
import { Route as AdminKitsRouteImport } from './routes/admin/kits'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminCheckProtocolsRouteImport } from './routes/admin/check-protocols'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminPurchaseOrdersIndexRouteImport } from './routes/admin/purchase-orders/index'
import { Route as AdminMasterDataIndexRouteImport } from './routes/admin/master-data/index'
import { Route as AdminPurchaseOrdersNewRouteImport } from './routes/admin/purchase-orders/new'
import { Route as AdminPurchaseOrdersOrderIdRouteImport } from './routes/admin/purchase-orders/$orderId'
import { Route as AdminMasterDataTemplatesRouteImport } from './routes/admin/master-data/templates'
import { Route as AdminMasterDataSuppliersRouteImport } from './routes/admin/master-data/suppliers'
import { Route as AdminMasterDataLocationsRouteImport } from './routes/admin/master-data/locations'
import { Route as AdminMasterDataDevicesRouteImport } from './routes/admin/master-data/devices'
import { Route as AdminMasterDataArticlesRouteImport } from './routes/admin/master-data/articles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetTokenRoute = PasswordResetTokenRouteImport.update({
  id: '/password-reset/$token',
  path: '/password-reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckTokenRoute = CheckTokenRouteImport.update({
  id: '/check/$token',
  path: '/check/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurchaseOrdersRoute = AdminPurchaseOrdersRouteImport.update({
  id: '/admin/purchase-orders',
  path: '/admin/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterDataRoute = AdminMasterDataRouteImport.update({
  id: '/admin/master-data',
  path: '/admin/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/admin/kits',
  path: '/admin/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckProtocolsRoute = AdminCheckProtocolsRouteImport.update({
  id: '/admin/check-protocols',
  path: '/admin/check-protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPurchaseOrdersIndexRoute =
  AdminPurchaseOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPurchaseOrdersRoute,
  } as any)
const AdminMasterDataIndexRoute = AdminMasterDataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMasterDataRoute,
} as any)
const AdminPurchaseOrdersNewRoute = AdminPurchaseOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPurchaseOrdersRoute,
} as any)
const AdminPurchaseOrdersOrderIdRoute =
  AdminPurchaseOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AdminPurchaseOrdersRoute,
  } as any)
const AdminMasterDataTemplatesRoute =
  AdminMasterDataTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AdminMasterDataRoute,
  } as any)
const AdminMasterDataSuppliersRoute =
  AdminMasterDataSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AdminMasterDataRoute,
  } as any)
const AdminMasterDataLocationsRoute =
  AdminMasterDataLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AdminMasterDataRoute,
  } as any)
const AdminMasterDataDevicesRoute = AdminMasterDataDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminMasterDataRoute,
} as any)
const AdminMasterDataArticlesRoute = AdminMasterDataArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminMasterDataRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/check-protocols': typeof AdminCheckProtocolsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/master-data': typeof AdminMasterDataRouteWithChildren
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/admin/master-data/articles': typeof AdminMasterDataArticlesRoute
  '/admin/master-data/devices': typeof AdminMasterDataDevicesRoute
  '/admin/master-data/locations': typeof AdminMasterDataLocationsRoute
  '/admin/master-data/suppliers': typeof AdminMasterDataSuppliersRoute
  '/admin/master-data/templates': typeof AdminMasterDataTemplatesRoute
  '/admin/purchase-orders/$orderId': typeof AdminPurchaseOrdersOrderIdRoute
  '/admin/purchase-orders/new': typeof AdminPurchaseOrdersNewRoute
  '/admin/master-data/': typeof AdminMasterDataIndexRoute
  '/admin/purchase-orders/': typeof AdminPurchaseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/check-protocols': typeof AdminCheckProtocolsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset': typeof PasswordResetIndexRoute
  '/admin/master-data/articles': typeof AdminMasterDataArticlesRoute
  '/admin/master-data/devices': typeof AdminMasterDataDevicesRoute
  '/admin/master-data/locations': typeof AdminMasterDataLocationsRoute
  '/admin/master-data/suppliers': typeof AdminMasterDataSuppliersRoute
  '/admin/master-data/templates': typeof AdminMasterDataTemplatesRoute
  '/admin/purchase-orders/$orderId': typeof AdminPurchaseOrdersOrderIdRoute
  '/admin/purchase-orders/new': typeof AdminPurchaseOrdersNewRoute
  '/admin/master-data': typeof AdminMasterDataIndexRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/check-protocols': typeof AdminCheckProtocolsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/master-data': typeof AdminMasterDataRouteWithChildren
  '/admin/purchase-orders': typeof AdminPurchaseOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/check/$token': typeof CheckTokenRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/password-reset/': typeof PasswordResetIndexRoute
  '/admin/master-data/articles': typeof AdminMasterDataArticlesRoute
  '/admin/master-data/devices': typeof AdminMasterDataDevicesRoute
  '/admin/master-data/locations': typeof AdminMasterDataLocationsRoute
  '/admin/master-data/suppliers': typeof AdminMasterDataSuppliersRoute
  '/admin/master-data/templates': typeof AdminMasterDataTemplatesRoute
  '/admin/purchase-orders/$orderId': typeof AdminPurchaseOrdersOrderIdRoute
  '/admin/purchase-orders/new': typeof AdminPurchaseOrdersNewRoute
  '/admin/master-data/': typeof AdminMasterDataIndexRoute
  '/admin/purchase-orders/': typeof AdminPurchaseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/account'
    | '/admin/check-protocols'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/master-data'
    | '/admin/purchase-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/password-reset/$token'
    | '/password-reset/'
    | '/admin/master-data/articles'
    | '/admin/master-data/devices'
    | '/admin/master-data/locations'
    | '/admin/master-data/suppliers'
    | '/admin/master-data/templates'
    | '/admin/purchase-orders/$orderId'
    | '/admin/purchase-orders/new'
    | '/admin/master-data/'
    | '/admin/purchase-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/account'
    | '/admin/check-protocols'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/settings'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/password-reset/$token'
    | '/password-reset'
    | '/admin/master-data/articles'
    | '/admin/master-data/devices'
    | '/admin/master-data/locations'
    | '/admin/master-data/suppliers'
    | '/admin/master-data/templates'
    | '/admin/purchase-orders/$orderId'
    | '/admin/purchase-orders/new'
    | '/admin/master-data'
    | '/admin/purchase-orders'
  id:
    | '__root__'
    | '/'
    | '/admin/account'
    | '/admin/check-protocols'
    | '/admin/inventory'
    | '/admin/kits'
    | '/admin/master-data'
    | '/admin/purchase-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/check/$token'
    | '/invitation/$token'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/password-reset/$token'
    | '/password-reset/'
    | '/admin/master-data/articles'
    | '/admin/master-data/devices'
    | '/admin/master-data/locations'
    | '/admin/master-data/suppliers'
    | '/admin/master-data/templates'
    | '/admin/purchase-orders/$orderId'
    | '/admin/purchase-orders/new'
    | '/admin/master-data/'
    | '/admin/purchase-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCheckProtocolsRoute: typeof AdminCheckProtocolsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminMasterDataRoute: typeof AdminMasterDataRouteWithChildren
  AdminPurchaseOrdersRoute: typeof AdminPurchaseOrdersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CheckTokenRoute: typeof CheckTokenRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  PasswordResetTokenRoute: typeof PasswordResetTokenRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/': {
      id: '/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/$token': {
      id: '/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/$token': {
      id: '/check/$token'
      path: '/check/$token'
      fullPath: '/check/$token'
      preLoaderRoute: typeof CheckTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purchase-orders': {
      id: '/admin/purchase-orders'
      path: '/admin/purchase-orders'
      fullPath: '/admin/purchase-orders'
      preLoaderRoute: typeof AdminPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/master-data': {
      id: '/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AdminMasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/admin/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-protocols': {
      id: '/admin/check-protocols'
      path: '/admin/check-protocols'
      fullPath: '/admin/check-protocols'
      preLoaderRoute: typeof AdminCheckProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/purchase-orders/': {
      id: '/admin/purchase-orders/'
      path: '/'
      fullPath: '/admin/purchase-orders/'
      preLoaderRoute: typeof AdminPurchaseOrdersIndexRouteImport
      parentRoute: typeof AdminPurchaseOrdersRoute
    }
    '/admin/master-data/': {
      id: '/admin/master-data/'
      path: '/'
      fullPath: '/admin/master-data/'
      preLoaderRoute: typeof AdminMasterDataIndexRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
    '/admin/purchase-orders/new': {
      id: '/admin/purchase-orders/new'
      path: '/new'
      fullPath: '/admin/purchase-orders/new'
      preLoaderRoute: typeof AdminPurchaseOrdersNewRouteImport
      parentRoute: typeof AdminPurchaseOrdersRoute
    }
    '/admin/purchase-orders/$orderId': {
      id: '/admin/purchase-orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/purchase-orders/$orderId'
      preLoaderRoute: typeof AdminPurchaseOrdersOrderIdRouteImport
      parentRoute: typeof AdminPurchaseOrdersRoute
    }
    '/admin/master-data/templates': {
      id: '/admin/master-data/templates'
      path: '/templates'
      fullPath: '/admin/master-data/templates'
      preLoaderRoute: typeof AdminMasterDataTemplatesRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
    '/admin/master-data/suppliers': {
      id: '/admin/master-data/suppliers'
      path: '/suppliers'
      fullPath: '/admin/master-data/suppliers'
      preLoaderRoute: typeof AdminMasterDataSuppliersRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
    '/admin/master-data/locations': {
      id: '/admin/master-data/locations'
      path: '/locations'
      fullPath: '/admin/master-data/locations'
      preLoaderRoute: typeof AdminMasterDataLocationsRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
    '/admin/master-data/devices': {
      id: '/admin/master-data/devices'
      path: '/devices'
      fullPath: '/admin/master-data/devices'
      preLoaderRoute: typeof AdminMasterDataDevicesRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
    '/admin/master-data/articles': {
      id: '/admin/master-data/articles'
      path: '/articles'
      fullPath: '/admin/master-data/articles'
      preLoaderRoute: typeof AdminMasterDataArticlesRouteImport
      parentRoute: typeof AdminMasterDataRoute
    }
  }
}

interface AdminMasterDataRouteChildren {
  AdminMasterDataArticlesRoute: typeof AdminMasterDataArticlesRoute
  AdminMasterDataDevicesRoute: typeof AdminMasterDataDevicesRoute
  AdminMasterDataLocationsRoute: typeof AdminMasterDataLocationsRoute
  AdminMasterDataSuppliersRoute: typeof AdminMasterDataSuppliersRoute
  AdminMasterDataTemplatesRoute: typeof AdminMasterDataTemplatesRoute
  AdminMasterDataIndexRoute: typeof AdminMasterDataIndexRoute
}

const AdminMasterDataRouteChildren: AdminMasterDataRouteChildren = {
  AdminMasterDataArticlesRoute: AdminMasterDataArticlesRoute,
  AdminMasterDataDevicesRoute: AdminMasterDataDevicesRoute,
  AdminMasterDataLocationsRoute: AdminMasterDataLocationsRoute,
  AdminMasterDataSuppliersRoute: AdminMasterDataSuppliersRoute,
  AdminMasterDataTemplatesRoute: AdminMasterDataTemplatesRoute,
  AdminMasterDataIndexRoute: AdminMasterDataIndexRoute,
}

const AdminMasterDataRouteWithChildren = AdminMasterDataRoute._addFileChildren(
  AdminMasterDataRouteChildren,
)

interface AdminPurchaseOrdersRouteChildren {
  AdminPurchaseOrdersOrderIdRoute: typeof AdminPurchaseOrdersOrderIdRoute
  AdminPurchaseOrdersNewRoute: typeof AdminPurchaseOrdersNewRoute
  AdminPurchaseOrdersIndexRoute: typeof AdminPurchaseOrdersIndexRoute
}

const AdminPurchaseOrdersRouteChildren: AdminPurchaseOrdersRouteChildren = {
  AdminPurchaseOrdersOrderIdRoute: AdminPurchaseOrdersOrderIdRoute,
  AdminPurchaseOrdersNewRoute: AdminPurchaseOrdersNewRoute,
  AdminPurchaseOrdersIndexRoute: AdminPurchaseOrdersIndexRoute,
}

const AdminPurchaseOrdersRouteWithChildren =
  AdminPurchaseOrdersRoute._addFileChildren(AdminPurchaseOrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminCheckProtocolsRoute: AdminCheckProtocolsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminMasterDataRoute: AdminMasterDataRouteWithChildren,
  AdminPurchaseOrdersRoute: AdminPurchaseOrdersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CheckTokenRoute: CheckTokenRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  PasswordResetTokenRoute: PasswordResetTokenRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
