ALTER TABLE `AlertSubscription`
  MODIFY `category` ENUM('EXPIRY', 'STK_DUE', 'MTK_DUE', 'SHORTAGE', 'KIT_CHECK_DUE') NOT NULL;

ALTER TABLE `AlertEvent`
  MODIFY `category` ENUM('EXPIRY', 'STK_DUE', 'MTK_DUE', 'SHORTAGE', 'KIT_CHECK_DUE') NOT NULL;
