import type { components } from "./generated-api";

export type UserRole = components["schemas"]["UserRole"];
export type KitOperationalStatus = components["schemas"]["KitOperationalStatus"];
export type ReplenishmentStatus = components["schemas"]["ReplenishmentStatus"];
export type AuthenticatedUser = components["schemas"]["AuthenticatedUser"];
export type SetupStatus = components["schemas"]["SetupStatus"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type InvitationPreview = components["schemas"]["InvitationPreview"];
export type PasswordResetPreview = components["schemas"]["PasswordResetPreview"];
export type UserSummary = components["schemas"]["UserSummary"];
export type Supplier = components["schemas"]["Supplier"];
export type Article = components["schemas"]["Article"];
export type Location = components["schemas"]["Location"];
export type TemplatePosition = components["schemas"]["TemplatePosition"];
export type KitTemplate = components["schemas"]["KitTemplate"];
export type Kit = components["schemas"]["Kit"];
export type Batch = components["schemas"]["Batch"];
export type InventoryMovement = components["schemas"]["InventoryMovement"];
export type InventoryAutomationConfig = components["schemas"]["InventoryAutomationConfig"];
export type InventoryTarget = components["schemas"]["InventoryTarget"];
export type PurchaseOrderStatus = components["schemas"]["PurchaseOrderStatus"];
export type PurchaseOrder = components["schemas"]["PurchaseOrder"];
export type ReplenishmentOrder = components["schemas"]["ReplenishmentOrder"];
export type PublicKitResponse = components["schemas"]["PublicKitResponse"];
export type CompleteCheckRequest = components["schemas"]["CompleteCheckRequest"];
export type CompleteCheckResponse = components["schemas"]["CompleteCheckResponse"];
export type CheckProtocolSummary = components["schemas"]["CheckProtocolSummary"];
export type CheckProtocolDetail = components["schemas"]["CheckProtocolDetail"];
export type CheckProtocolListResponse = {
  items: CheckProtocolSummary[];
  page: number;
  pageSize: number;
  total: number;
  totalCount: number;
};
export type FulfillOrderRequest = components["schemas"]["FulfillOrderRequest"];
export type FulfillOrderResponse = components["schemas"]["FulfillOrderResponse"];
export type CreateArticleRequest = components["schemas"]["CreateArticleRequest"];
export type CreateSupplierRequest = components["schemas"]["CreateSupplierRequest"];
export type CreateLocationRequest = components["schemas"]["CreateLocationRequest"];
export type CreateTemplateRequest = components["schemas"]["CreateTemplateRequest"];
export type CreateBatchRequest = components["schemas"]["CreateBatchRequest"];
export type CreateKitRequest = components["schemas"]["CreateKitRequest"];
export type UpdateArticleRequest = components["schemas"]["UpdateArticleRequest"];
export type UpdateSupplierRequest = components["schemas"]["UpdateSupplierRequest"];
export type UpdateLocationRequest = components["schemas"]["UpdateLocationRequest"];
export type ReviseTemplateRequest = components["schemas"]["ReviseTemplateRequest"];
export type UpdateKitRequest = components["schemas"]["UpdateKitRequest"];
export type BatchCorrectionRequest = components["schemas"]["BatchCorrectionRequest"];
export type PurchaseOrderWriteRequest = components["schemas"]["PurchaseOrderWriteRequest"];
export type UpdatePurchaseOrderRequest = components["schemas"]["UpdatePurchaseOrderRequest"];
export type CreatePurchaseOrdersFromShortagesRequest = components["schemas"]["CreatePurchaseOrdersFromShortagesRequest"];
export type ReceivePurchaseOrderRequest = components["schemas"]["ReceivePurchaseOrderRequest"];
export type UpsertInventoryTargetRequest = components["schemas"]["UpsertInventoryTargetRequest"];
export type UpdateInventoryAutomationConfigRequest = components["schemas"]["UpdateInventoryAutomationConfigRequest"];
export type InviteUserRequest = components["schemas"]["InviteUserRequest"];
